version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
      - ./html:/var/www/html 
    depends_on:
      - php 

  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html 
    expose:
      - "9000" 
