name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main  # ทำงานเมื่อ Push ไปยัง Branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # ใช้ credentials จาก GitHub Secrets

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '330.0.0'  # ใช้เวอร์ชันอื่น เช่น '330.0.0'
        project_id: 'triple-env-447304-f9'  # กำหนด project ID ที่ใช้

    - name: Deploy to VM
      run: |
        gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
