name: Deploy to Server

on:
  push:
    branches:
      - main  # รันเมื่อ push ไปที่ branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp://ftp.example.com  # URL เซิร์ฟเวอร์ FTP
        username: ${{ secrets.FTP_USERNAME }}  # Username จาก Secrets
        password: ${{ secrets.FTP_PASSWORD }}  # Password จาก Secrets
        local-dir: ./  # ไฟล์ที่ต้องอัปโหลด
        server-dir: /var/www/html  # ไฟล์ปลายทาง
