name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
 
    - name: Set up Google Cloud SDK
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcloud-service-key.json"
        cat "${HOME}/gcloud-service-key.json"  # ตรวจสอบว่าไฟล์ JSON ถูกต้อง
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
        gcloud config set project triple-env-447304-f9

    - name: Deploy to VM
      run: |
        gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
  