name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      run: |
        curl https://sdk.cloud.google.com | bash  # ติดตั้ง gcloud CLI
        source ~/.bashrc
        gcloud --quiet auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}  # ใช้ Service Account Key
        gcloud config set project triple-env-447304-f9  # ตั้งค่าคอนฟิก Google Cloud

    - name: Deploy to VM
      run: |
        gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
