name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # ใช้เวอร์ชันที่ถูกต้อง
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # ใช้ Secret สำหรับ Service Account Key

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        cp /home/runner/.ssh/google_compute_engine ~/.ssh/google_compute_engine
        chmod 600 ~/.ssh/google_compute_engine
        ssh-keyscan -H 35.234.0.0 >> ~/.ssh/known_hosts  # เพิ่ม host key สำหรับ Google Cloud
        
    - name: Deploy to VM
      run: |
        gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
