name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # ใช้เวอร์ชันที่ถูกต้อง
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # ใช้ Secret สำหรับ Service Account Key

    - name: Deploy to VM
      run: |
        # สร้าง SSH key และกำหนดสิทธิ์ให้ถูกต้อง
        mkdir -p ~/.ssh
        gcloud auth activate-service-account --key-file="${{ secrets.GCP_SA_KEY }}"
        
        # ใช้ gcloud สำหรับการตั้งค่า SSH key และเชื่อมต่อไปยัง VM
        gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
