name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      run: |
        # Decode the service account key from base64 and save it to a file
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > "${HOME}/gcloud-service-key.json"
        
        # Activate the service account and set the project
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
        gcloud config set project triple-env-447304-f9

    - name: Deploy to VM
      run: |
        # SSH into the VM and run the necessary commands
        gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
