name: Deploy to Server

on:
  push:
    branches:
      - main  # รันเมื่อ push ไปที่ branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp://ftp.example.com  # URL ของ FTP Server
        username: ${{ secrets.FTP_USERNAME }}  # Secrets สำหรับ username
        password: ${{ secrets.FTP_PASSWORD }}  # Secrets สำหรับ password
        local-dir: ./  # โฟลเดอร์ต้นทาง
        server-dir: /var/www/html  # โฟลเดอร์ปลายทาง
